### ISSUE TITLE
Feedback on service design in schools post

### ISSUE THREAD

**Issue by andysylvester** [gboone/gboone.github.io#16]
Re: https://greg.harmsboone.org/2015/10/27/service-design-in-the-schools/

Greg,

I like your idea of having school groups do service design projects (found your post through Melody Kramer's newsletter). Do you have suggestions for how school groups (or any kind of group) could find problems to solve using software? I took at look at CodeForAmerica.org and found this page of issues/projects (http://www.codeforamerica.org/geeks/civicissues), would be interested in your thoughts.

Andy Sylvester
andy@andysylvester.com

**Comment by gboone** [comment]
Thanks for the comment, @andysylvester, and thanks for reading. I really like the CFA Civic Issue tracker and I think it could be a good way to find opportunities to get involved in the project.

That's a really great question. When I wrote that blog post I imagined something very direct, where students somehow reached out to teachers, staff, administrators, or other students to find and understand problems that need solving, with the goal to better understand the users and the needs they face before attempting to build a solution.

When I had the idea, I had the luxury of being able to watch my mother in-law work with these swim results enough to get curious and start asking questions and I think that's probably key. Whoever is facilitating will want to give the students time to simply observe and ask questions of the people encountering the problem they want to solve. It's a little ethnographic, and I think that's why I like i :wink:

Thanks again for reading!

**Comment by KatherineMichel** [comment]
Hi Greg,

Andy emailed me and asked me if I have any thoughts on this. I have spent some time studying service design resources and like to curate my [favorite resources](https://github.com/KatherineMichel/tech-and-venture-capital-toolkit/blob/master/README.md#research-and-design-sprints). On a small scale, a portal such as CFA Issue Tracker would not be needed. A project could be initiated as simply as a faculty member communicating a problem to the school's service design team. However, if the project would be of interest to people outside the school (a project that solves a problem experienced by other schools, or that demonstrates some learning that would be useful to other schools), then maybe it would be good to share projects, processes, results online, and perhaps even remotely collaborate. In addition to CFA Issue Tracker, the [18F Midas tool, now called Open Opportunities Platform](https://github.com/18F/openopps-platform) also comes to mind as a concept that could be modified to provide an interface for connecting a proposed project with a group of students. Definitely with all of the service design methodologies that exist, there is not a shortage of material to use to create a structured process that would develop the student's skills while they work to create innovation. Here are a few resources that immediately came to mind: 

*   [Google Ventures Design Sprint](http://www.gv.com/sprint)
*   [Design Sprint Book](http://www.designsprintbook.com)
*   [Thoughtbot Playbook Design Sprint](http://playbook.thoughtbot.com/#product-design-sprint) and [Thoughtbot Design Sprint- Materials GitHub](https://github.com/thoughtbot/design-sprint)
*   [Eric Ries: Lean Startup](http://www.amazon.com/gp/product/0307887898)
*  Steve Blank Customer Discovery Checklist (part of the Startup Owners Manual, a little bit off topic but a detailed process related to Lean Startup)
*   [Australia Digital Transformation Office Design Guides](https://www.dto.gov.au/design-guides)
*   [U.K. Government Service Design Manual](https://www.gov.uk/service-manual)
*   [U.S. CIO Playbook](http://playbook.cio.gov)
*   [18F Guides](https://pages.18f.gov/guides)
*   [Code for America](http://www.codeforamerica.org)
*   [Government Usability](http://www.usability.gov)

Thank you,
Kati Michel
